@startuml HiEffectImage

page 2x2
skinparam PageMargin 10
skinparam PackageStyle rectangle

interface CGRect {
}

package "HiImageEditor.Core" {

    interface HEResizable {
        + float resized
        + void resize(float factor)
    }
    interface HETranslatable {
        + CGRect frame
        + void tranlate(int x, int y)
    }
    interface HERotatable {
        + float rotated
        + void rotate(float angle)
    }
    interface HECroppable {
        + void crop(int x, int y, int width, int height)
    }
    interface HETransfomable {
    }
    
    CGRect <|-- HECroppable
    HERotatable <|-- HETransfomable
    HETranslatable <|-- HETransfomable
    HEResizable <|-- HETransfomable
}

@enduml